title: 'ALX AICE'
description: 'A site documenting my learnings from an online course.'
baseurl: '' # the subpath of your site, e.g., /blog
url: 'https://fasakinhenry.github.io/ALX_AICE' # the base hostname & protocol for your site
theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes

# Minimal Mistakes settings
sidebar:
  nav: 'navigation' # Use the navigation.yml file in the _data folder

# Repository settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
